[build]
  command = "next build"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"
  package = "@netlify/plugin-nextjs"


[context.production]
  command = "next build"
[context.production.environments]
  BASE_URL = "https://datascience.terminology.me"
